[target.aarch64-linux-android]
ar = "/opt/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar"
ranlib = "/opt/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ranlib"

[target.aarch64-linux-android.env]
ANDROID_NDK_ROOT = "/opt/android-sdk/ndk/25.2.9519653"
